#!/bin/bash

echo 'Adding Unifi Source List...'
echo 'deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti' | sudo tee /etc/apt/sources.list.d/100-ubnt-unifi.list
echo
echo
echo 'Downloading and Installing Trusted Key'
sudo wget -O /etc/apt/trusted.gpg.d/unifi-repo.gpg https://dl.ubnt.com/unifi/unifi-repo.gpg 
echo
echo
echo
echo 'Updating Repos'
sudo apt-get update 
echo 'Installing Unifi Controller'
sudo apt-get install unifi -y
echo 'Unifi Server is now installed. Access the Controller via https://<server IP>:8443'
echo 'Manually run discovery by entering the following command: java -jar /usr/lib/unifi/lib/ace.jar'
echo
